---
title: "Renewable Energy and Sustainable Infrastructure"
author: PRISMS Team
date: November, 2017
output:
  ioslides_presentation: 
    logo: PRISMS_Logo.png
    fig_caption: yes
    keep_md: yes
    smaller: yes
    widescreen: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = T)
```

## Data Description
http://open.canada.ca/data/en/dataset/7e50d70e-f462-48ea-97f5-6c0bc48cfd14 

## Load Library
```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(knitr)
library(kableExtra)
library(gridExtra)
```

## Import Datasets
```{r message=FALSE}
RE_Capacity <- read_csv("Data/Renewable_energy_Capacity.csv")
RE_Generation <- read_csv("Data/Renewable_energy_Generation.csv")
RE_Dictionary <- read_csv("Data/RE_Dictionary.csv")
```

## Tidy Datasets
```{r}
RE_Capacity <- RE_Capacity %>%
  rename(Data_Capacity = Data) %>%
  unite(RSV, Region, Source, Year)

RE_Generation <- RE_Generation %>%
  rename(Data_Generation = Data) %>%
  unite(RSV, Region, Source, Year)

RE_Full <- full_join(RE_Capacity, RE_Generation, by = "RSV") %>%
  separate(RSV, into = c("Region", "Source", "Year"), sep = "_") %>%
  rename(Capacity_MW = Data_Capacity) %>%
  rename(Generation_GWh = Data_Generation) %>%
  select(-Unit.x, -Unit.y)
```

## Renewable Energy Dataset
```{r}
kable(RE_Full, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width = "90%", height = "400px")
```

## Dataset Dictionary
```{r}
kable(RE_Dictionary, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  scroll_box(width = "90%", height = "400px")
```

## First Basic Plot
```{r warning=FALSE}
ggplotly(ggplot(RE_Full, aes(x = Capacity_MW, y = Generation_GWh)) +
  geom_point(aes(color = Source)))
```

## Generation vs. Year
```{r warning=FALSE}
ggplotly(ggplot(RE_Full %>% filter(Region == "BC"), aes(Year, Generation_GWh)) +
  geom_point() +
  facet_grid(Source ~ .))
```

## Generation vs. Year in facets
```{r warning=FALSE}
# Generation_GWh<=10000
Data <- filter(RE_Full, Region == "BC") 

ggplotly(ggplot(Data, mapping = aes(x = Year, y = Generation_GWh))+
  geom_point() +
  facet_wrap(~Source, ncol = 5) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)))
```

##shiny graph test
```{r}
RE_Full %>%
  filter(Region == "BC") %>%

ggplot(aes(x = Year, y = Capacity_MW)) +
  geom_point()+
  facet_wrap(~Source) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

mutate(renewable = ifelse(Source = c("Solar", ), "T", "F"))
```
```{r}
#Renewable: biomass, hydro, solar, wind
#Others: Coal, Natural Gas, Nuclear, Oil

t1 <- RE_Full %>%
  filter(Region == "BC") %>%
  filter(Source == "Renewables") %>%
ggplot(aes(x = Year, y = Capacity_MW)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Capacity(Megawatts, Renewable)")

t2 <- RE_Full %>%
  filter(Region == "BC") %>%
  filter(Source == c("Coal", "Natural Gas", "Nuclear", "Oil")) %>%
  group_by(Year) %>%
  summarise(avg_capacity = mean(Capacity_MW)) %>%
ggplot(aes(x = Year, y = avg_capacity)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Capacity(Megawatts, Non-renewable)")

grid.arrange(t1, t2, ncol=2)
```
```{r}
t1 <- RE_Full %>%
  filter(Region == "YT") %>%
  filter(Source == "Renewables") %>%
ggplot(aes(x = Year, y = Capacity_MW)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Capacity(Megawatts, Renewable)")

t2 <- RE_Full %>%
  filter(Region == "YT") %>%
  filter(Source == c("Coal", "Natural Gas", "Nuclear", "Oil")) %>%
  group_by(Year) %>%
  summarise(avg_capacity = mean(Capacity_MW)) %>%
ggplot(aes(x = Year, y = avg_capacity)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Capacity(Megawatts, Non-renewable)")

grid.arrange(t1, t2, ncol=2)
```

